export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_OK = "ADD_EMPLOYEE_OK";
export const ADD_EMPLOYEE_ERROR = "ADD_EMPLOYEE_ERROR";

export const BEGIN_EMPLOYEES_DOWNLOAD = "BEGIN_EMPLOYEES_DOWNLOAD";
export const EMPLOYEES_DOWNLOAD_OK = "EMPLOYEES_DOWNLOAD_OK";
export const EMPLOYEES_DOWNLOAD_ERROR = "EMPLOYEES_DOWNLOAD_ERROR";

export const RETRIEVE_EMPLOYEE_DELETE = "RETRIEVE_EMPLOYEE_DELETE";
export const EMPLOYEE_DELETED_OK = "EMPLOYEE_DELETED_OK";
export const EMPLOYEE_DELETED_ERROR = "EMPLOYEE_DELETED_ERROR";

export const RETRIEVE_EMPLOYEE_EDIT = "RETRIEVE_EMPLOYEE_EDITED";
export const BEGIN_EDIT_EMPLOYEE = "BEGIN_EDIT_EMPLOYEE";
export const EMPLOYEE_EDITED_OK = "EMPLOYEE_EDITED_OK";
export const EMPLOYEE_EDITED_ERROR = "EMPLOYEE_EDITED_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
